spring:
  cloud:
    gcp:
      project-id: foo-bar
      # make sure to disable this property first
      # credentials:
      #   encoded-key: <<put-your-encoded-key-here>>
      sql:
        enabled: true
        database-name: test
        instance-connection-name: foo-bar:europe-west4:some-database
        enable-iam-auth: true
  datasource:
    username: dluijk@bol.com

# custom property is needed
demo:
  gcp:
    credentials.encoded-key: <<put-your-encoded-key-here>>